### ISSUE TITLE
flywaydb JdbcUtils can't connect to H2

### ISSUE THREAD

**Issue by cobar79** [radcortez/flyway-junit5-extensions#247]
schema is created but can't connect to execute SQL.

PROVIDER:
`import com.radcortez.flyway.test.junit.DataSourceProvider;
import com.radcortez.flyway.test.junit.DataSourceInfo;
import lombok.extern.slf4j.Slf4j;
import org.eclipse.microprofile.config.Config;
import org.eclipse.microprofile.config.ConfigProvider;
import org.junit.jupiter.api.extension.ExtensionContext;

@Slf4j
public class H2DatasourceProvider implements DataSourceProvider {

    @Override
    public DataSourceInfo getDatasourceInfo(final ExtensionContext extensionContext) {
        // Quarkus Dev Services rewrite the Dev Service datasource in the configuration
        Config config = ConfigProvider.getConfig();
        String url = config.getValue("quarkus.datasource.jdbc.url", String.class);
        String username = config.getValue("quarkus.datasource.username", String.class);
        String password = ""; //NOT REQUIRED BY H2 config.getValue("quarkus.datasource.password", String.class);
        log.info("TEST Datasource at URL [{}], user [{}], pw [{}]", url, username, password);
        return DataSourceInfo.config(url, username, password);
    }
}
`

TEST CLASS:
`
@QuarkusTest
@Tag("integration")
@TestProfile(TestConfigProfile.class)
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@FlywayTest(@DataSource(H2DatasourceProvider.class))
`

RESULTS
`
"2022-07-15 12:38:19,341 INFO  (main) [io.quarkus.printStartupTime()] Installed features: [agroal, cdi, config-yaml, hibernate-orm, jdbc-h2, jdbc-postgresql, narayana-jta, rest-client, resteasy, resteasy-jackson, resteasy-multipart, scheduler, security, security-jdbc, security-properties-file, smallrye-context-propagation, smallrye-fault-tolerance, vertx]
"2022-07-15 12:38:19,406 INFO  (main) [com.bluestaq.marketplace.config.H2DatasourceProvider.getDatasourceInfo()] TEST Datasource at URL [jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS market], user [sa], pw []
2022-07-15 12:38:19,739 WARN  (main) [org.flywaydb.core.internal.jdbc.JdbcUtils.warn()] Connection error: Wrong user name or password [28000-197] Retrying in 1 sec...
`

**Comment by radcortez** [comment]
Hi @cobar79,

If you are running with Quarkus DevServices, an actual password is generated, so you cannot pass `""` as the password. You need to use `quarkus.datasource.username`.

**Comment by cobar79** [comment]
@radcortez thanks for the response. 

When I have the ```quarkus.datasource.password``` in the properties:
```
java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.get(Optional.java:148)
        at io.quarkus.test.junit.RunningAppConfigResolver$1.getValue(RunningAppConfigResolver.java:27)
```

That is why I attempted to pass it directing into the ```DataSourceInfo.config(url, username, password)``` since H2 doesn't require a password.

**Comment by radcortez** [comment]
Do you have a reproducer I can look at? I tried it with my test, and it works fine for me. Thanks!

**Comment by cobar79** [comment]
Can you elaborate on "If you are running with Quarkus DevServices, **an actual password is generated**, so you cannot pass as the password." If it is generated, then how do you pass this generated value in the DataSourceInfo?

Assumption, the default username=sa, password=  

So I did some isolation testing and if I do a ```java.sql.DriverManager.getConnection(url, username, pw)``` I get invalid username password.

If I use the extension and let the ```org.flywaydb.core.internal.jdbc.JdbcUtils``` use the ```javax.sql.DataSource``` configured from your ```DataSourceInfo``` same results. 

However, if I use  ``` org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(datasource)``` using the ```@Injected io.agroal.pool.DataSource``` from the Quarkus context I can connect to the H2 instance.

So the question is. Can we pass the ```@Injected io.agroal.pool.DataSource``` directly to Flyway rather than via the ```DataSourceInfo```?

```
package com.bar

import com.radcortez.flyway.test.annotation.FlywayTest;
import com.radcortez.flyway.test.junit.DataSourceInfo;
import com.radcortez.flyway.test.junit.DataSourceProvider;
import io.quarkus.test.common.QuarkusTestResource;
import io.quarkus.test.h2.H2DatabaseTestResource;
import io.quarkus.test.junit.QuarkusTest;
import io.quarkus.test.junit.TestProfile;
import lombok.extern.slf4j.Slf4j;
import org.eclipse.microprofile.config.Config;
import org.eclipse.microprofile.config.ConfigProvider;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.extension.ExtensionContext;

import javax.inject.Inject;
import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

@Slf4j
@QuarkusTest
@Tag("integration")
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
//@FlywayTest(@com.radcortez.flyway.test.annotation.DataSource(H2Test.H2DatasourceProvider.class))
//@QuarkusTestResource(H2DatabaseTestResource.class)
public class H2Test {

    @Inject
    DataSource datasource;

    @BeforeAll
    public void beforeAll() {
        log.info("DATASOURCE:: " + datasource + " instance of " + datasource.getClass().getName());
    }

    @Test
    public void testH2DbMem() throws SQLException {
        testDatabase("jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS;");
    }

    private void testDatabase(String url) throws SQLException {
        //Connection connection = DriverManager.getConnection(url, "sa", "");
        //Connection connection = datasource.getConnection();
        Connection connection = org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(datasource, 2, 2);
        insert(connection);
        select(connection);
        connection.close();
    }

    private void insert(Connection connection) throws SQLException {
        Statement st = connection.createStatement();
        String sql = "INSERT INTO .Country" +
                "(code, name, codeAlt, createdAt, createdBy, updatedAt, updatedBy, source, version) VALUES" +
                " ('US', 'United States of America', 'USA', current_timestamp, 'test', NULL, NULL, 'ISO', 0)";
        st.executeUpdate(sql);
    }

    private void select(Connection connection) throws SQLException {
        try (PreparedStatement ps = connection.prepareStatement("select count(*) from .Country"); ResultSet r = ps.executeQuery()) {
            log.info("Handle result set");
            while (r.next()) {
                log.info("Country count = " + r.getInt(1));
            }
        } catch (SQLException e) {
            log.error(e.getMessage());
            throw e;
        }
    }

    @Slf4j
    public static class H2DatasourceProvider implements DataSourceProvider {

        @Override
        public DataSourceInfo getDatasourceInfo(final ExtensionContext extensionContext) {
            // Quarkus Dev Services rewrite the Dev Service datasource in the configuration
            Config config = ConfigProvider.getConfig();
            String url = config.getValue("quarkus.datasource.jdbc.url", String.class);
            String username = "sa"; //config.getValue("quarkus.datasource.username", String.class);
            String password = ""; //config.getValue("quarkus.datasource.password", String.class); //null pointer on option.
            log.info("TEST Datasource at URL [{}], user [{}], pw [{}]", url, username, password);
            return DataSourceInfo.config(url, username, password);
        }
    }
}
```
```

**Comment by cobar79** [comment]
Issue with our application in the way it loads credentials from external manually loaded file.

**Comment by radcortez** [comment]
You need to upgrade to H2 2.x version. I'm using `2.1.214`.
